env:
  global:
    - secure: "jRAtqz7/FgvkqQgaWTY3d50Ad1tW9m3U4/XAqHowRGGUJvWw+A5a207og0s+ZoBi3D5NnyOaLG1HlCqPqvjjB4WhkYz4awvL/rES338RcxdSk7q5lA06lHT1jJxbOINSZsHT5hWUw01Tb71LOi22FAt0qiZI7eigx/zV2PGNFhZCkyJef8Naz1x3s+rarZBgYJv9TnkumxIw9+Vpfm+0q/ldyAt97BqUA3v23ZCBrOXPeRIo/GsuQCWKVWbdvTYu6UCzsykOAkt6lmFoXc3h+k2wLeouf1EoupgbQV1MM9gMvnCRrfA5PJfED+b4qW498z/16WiKSzjUshg7y0F7kMjoMQwMWl4xds9T2PH5ox02HK91LpX+qBsSM1Dm4LzaN1VouQNI2UYYW1sYXcbFmmxXQXdM5TIuaUbzQ573J/p2MWoNf7U80ga2Xhjd/8sAs+Z73TAfCVoIN1vjFvoNvPLfrWaVttsQ8ykXm1LeGvm4+JLBe9EagAmkn0sYT3w0vhlZBmcYD7zW2I4/nZKKU4nLmc98bdzDq2z2Tu3h31N8Yx9S0VQPLAXx721tXK7AdpKuPM1++Pj8fM1PODFWamx9ahaytq4GGLC7hX+2wscd/4uVkLNeD9LvaixqMB7czH/lB7/BMQtcrq48mzJT8YKxz9c3k8NO1I0dnuI2+0s="
    - secure: "j6Vp8V8716nDcCRzXZDSzaBAF7FYX4i7QLye+xNdGVttnrYwUv7weZbEkHTDcP/vlztj8MnJAq0iDiDv0TBDjeQnObcl3weYhz7xthPKU1ySiNwevbtjpQqtAsTkhy5LWmx/rklc1hwa+xxtSwUWF58V/3+9fiprluy6TmBu0wJ+sWnHUGRQDO7zDSdME2NqjzgtD/6cXEMelaoX+YJup2d/yFGanE6S+P69zJXEMwURMxeeWQymD+Gx3vVmdmXM7CxeJva5IgcPgv+SeXzUulRfslLVlhUjaw6BexDSPh/EEejIspPkJjqlERKYnt7CS/PE/MuROGBeVwUXOMibpi5wTngCC8MmOyyfEsMMqtsLDAb160Rh9Jr/1TcuzHCwV3venBKfJjWUtp6hLx8IjXXxoiHg0b8Btp+V9HCtWWaZ7WAISvTyV+zh3CaUg4f7ZMkEUZn+FwFojyqswfbE9QQvsIsOtDbqE+3mhZIlFFNml/L3LmJfk3Nqx1oX24dRt+byR6GIlUjcgUV4ueMtDUxKNSd93hcdTpCTcTepPiLypPORTl/qRX8soqZTEYoIhtC0Hc7UZOtaV2UHv8iULiITVdmLyXFSVdkTkthQ/ETqK4rIQiYixmJBihqnNAJXxyPQCaTFJqdy1625qZKWTjwSoORy/U7BYh4MDDxdP/k="

language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=sketch sketch_tests.py
after_success:
  - coveralls
  - export DEPLOY_CONTENT='{"TRAVIS_BUILD_NUMBER":"'$TRAVIS_BUILD_NUMBER'","TRAVIS_COMMIT":"'$TRAVIS_COMMIT'"}'
  - export DEPLOY_SIG="sha1=`echo $DEPLOY_CONTENT | openssl sha1 -hmac $DEPLOY_KEY`"
  - >
    curl -X POST "$DEPLOY_URL" --data $DEPLOY_CONTENT -H "Content-Type: application/json" -H "X-Trav-Signature: $DEPLOY_SIG"
